using JoyMap.Extensions;
using JoyMap.Profile;
using JoyMap.Windows;

namespace JoyMap
{
    public partial class ActionForm : Form
    {
        public ActionForm(EventAction? effect = null)
        {
            InitializeComponent();
            comboSimpleKey.Configure(KeyOrButton.All);
            comboOnChangeKey.Configure(KeyOrButton.All);




            if (effect is not null)
            {
                textName.Text = effect.Name;
                textDelay.Text = effect.DelayMs.ToStr();

                if (effect.SimpleInputEffect is not null)
                {
                    SimpleKey = effect.SimpleInputEffect.Keys;
                    comboSimpleKey.SelectedItem = SimpleKey;
                    if (effect.SimpleInputEffect.AutoTriggerFrequency is not null)
                    {
                        cbSimpleAutoTriggerFrequency.Checked = true;
                        textSimpleAutoTriggerFrequency.Text = effect.SimpleInputEffect.AutoTriggerFrequency.Value.ToStr();
                    }
                    if (effect.SimpleInputEffect.AutoTriggerLimit is not null)
                    {
                        cbSimpleAutoTriggerLimit.Checked = true;
                        textSimpleAutoTriggerLimit.Text = effect.SimpleInputEffect.AutoTriggerLimit.Value.ToString();
                    }
                    if (effect.SimpleInputEffect.AutoTriggerDelayMs is not null)
                    {
                        cbSimpleAutoTriggerDelayedStart.Checked = true;
                        textSimpleAutoTriggerDelayedStartMs.Text = effect.SimpleInputEffect.AutoTriggerDelayMs.Value.ToStr();
                    }
                    tabControl.SelectedTab = tpSimple;
                }
                else if (effect.ChangeTriggeredInputEffect is not null)
                {
                    TriggerKey = effect.ChangeTriggeredInputEffect.Keys;
                    comboOnChangeKey.SelectedItem = TriggerKey;
                    tabControl.SelectedTab = tpTrigger;

                }
                AutoGeneratedName = GenerateName();

                Rebuild();
            }
        }

        private string AutoGeneratedName { get; set; } = "";
        private KeyOrButton SimpleKey { get; set; }
        private KeyOrButton TriggerKey { get; set; }

        public EventAction? Result { get; private set; }

        private void btnSimplePickKey_Click(object sender, EventArgs e)
        {

            using var form = new PickKeyForm();
            if (form.ShowDialog() == DialogResult.OK)
            {
                SimpleKey = KeyOrButton.From(form.Result);
                comboSimpleKey.SelectedItem = SimpleKey;
                Rebuild();
            }

        }

        private void Rebuild()
        {
            btnOk.Enabled = false;



            var delay = textDelay.GetFloat(false);
            if (delay is null || delay.Value < 0)
            {
                toolStripStatusLabel.Text = $"Unable to parse trigger delay";
                return;
            }

            if (textName.Text == AutoGeneratedName)
            {
                AutoGeneratedName = GenerateName();
                textName.Text = AutoGeneratedName;
            }
            if (string.IsNullOrWhiteSpace(textName.Text))
            {
                toolStripStatusLabel.Text = $"Trigger name is not set";
                return;
            }

            if (tabControl.SelectedTab == tpSimple)
            {


                var autoTriggerDelayedStartMs = textSimpleAutoTriggerDelayedStartMs.GetFloat(false);
                var triggerFrequency = textSimpleAutoTriggerFrequency.GetFloat(false);
                var autoTriggerLimit = textSimpleAutoTriggerLimit.GetInt();
                if (!cbSimpleAutoTriggerFrequency.Checked)
                {
                    triggerFrequency = null;
                }
                if (!cbSimpleAutoTriggerDelayedStart.Checked)
                {
                    autoTriggerDelayedStartMs = null;
                }
                else if (triggerFrequency is null || triggerFrequency.Value <= 0)
                {
                    toolStripStatusLabel.Text = $"Unable to parse trigger frequency";
                    return;
                }
                if (!cbSimpleAutoTriggerLimit.Checked || !cbSimpleAutoTriggerLimit.Checked)
                    autoTriggerLimit = null;
                else if (autoTriggerLimit is null)
                {
                    toolStripStatusLabel.Text = $"Trigger limit is enabled but limit is not set";
                    return;
                }


                var key = comboSimpleKey.SelectedItem as KeyOrButton?;
                if (key is null)
                {
                    toolStripStatusLabel.Text = $"Simple trigger key/button is not set";
                    return;
                }

                Result = new EventAction(
                    textName.Text.Trim(),
                    delay.Value,
                    SimpleInputEffect: new SimpleInputEffect
                    (
                        Keys: key.Value,
                        AutoTriggerDelayMs: autoTriggerDelayedStartMs,
                        AutoTriggerFrequency: triggerFrequency,
                        AutoTriggerLimit: autoTriggerLimit
                    )
                    );
            }
            else if (tabControl.SelectedTab == tpTrigger)
            {

                var key = comboOnChangeKey.SelectedItem as KeyOrButton?;
                if (key is null)
                {
                    toolStripStatusLabel.Text = $"On-change trigger key/button is not set";
                    return;
                }


                Result = new EventAction(
                    textName.Text.Trim(),
                    delay.Value,
                    ChangeTriggeredInputEffect: new ChangeTriggerInputEffect
                    (
                        Keys: key.Value
                    )
                    );
            }
            else
            {
                toolStripStatusLabel.Text = $"Bad effect selection";
                return;
            }
            toolStripStatusLabel.Text = $"Ok";
            btnOk.Enabled = true;

        }

        private string GenerateName()
        {
            if (tabControl.SelectedTab == tpSimple)
            {
                float? triggerFrequency;
                if (!cbSimpleAutoTriggerFrequency.Checked)
                {
                    triggerFrequency = null;
                }
                else
                    triggerFrequency = textSimpleAutoTriggerFrequency.GetFloat(false);
                return $"{comboSimpleKey.Text}{(triggerFrequency is not null ? " (auto)" : "")}";
            }
            if (tabControl.SelectedTab == tpTrigger)
            {
                return comboOnChangeKey.Text;
            }
            return "";
        }

        private void btnOk_Click(object sender, EventArgs e)
        {
        }

        private void AnyInputChanged(object sender, EventArgs e)
        {
            Rebuild();
        }

        private void textSimpleAutoTriggerFrequency_TextChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerFrequency.Checked = true;
            AnyInputChanged(sender, e);
        }

        private void textAutoTriggerLimit_TextChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerLimit.Checked = true;
            AnyInputChanged(sender, e);
        }

        private void cbSimpleAutoTriggerFrequency_CheckedChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerDelayedStart.Enabled =
                cbSimpleAutoTriggerLimit.Enabled =
                textSimpleAutoTriggerLimit.Enabled =
                textSimpleAutoTriggerDelayedStartMs.Enabled =
                cbSimpleAutoTriggerFrequency.Checked;


            AnyInputChanged(sender, e);
        }

        private void cbSimpleAutoTriggerLimit_CheckedChanged(object sender, EventArgs e)
        {
            AnyInputChanged(sender, e);
        }

        private void cbSimpleAutoTriggerDelayedStart_CheckedChanged(object sender, EventArgs e)
        {
            AnyInputChanged(sender, e);
        }

        private void textSimpleAutoTriggerDelayedStartMs_TextChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerDelayedStart.Checked = true;
            AnyInputChanged(sender, e);

        }

        private void btnChangeTriggerKeySelect_Click(object sender, EventArgs e)
        {

            using var form = new PickKeyForm();
            if (form.ShowDialog() == DialogResult.OK)
            {
                TriggerKey = KeyOrButton.From(form.Result);
                comboOnChangeKey.SelectedItem = TriggerKey;
                Rebuild();
            }

        }
    }
}
