using JoyMap.Extensions;
using JoyMap.Profile;

namespace JoyMap
{
    public partial class ActionForm : Form
    {
        public ActionForm(EventAction? effect = null)
        {
            InitializeComponent();
            if (effect is not null)
            {
                textName.Text = effect.Name;
                textDelay.Text = effect.DelayMs.ToStr();

                if (effect.SimpleInputEffect is not null)
                {
                    SimpleKey = effect.SimpleInputEffect.Keys;
                    textSimpleKey.Text = PickKeyForm.KeysToString(SimpleKey);
                    if (effect.SimpleInputEffect.AutoTriggerFrequency is not null)
                    {
                        cbSimpleAutoTriggerFrequency.Checked = true;
                        textSimpleAutoTriggerFrequency.Text = effect.SimpleInputEffect.AutoTriggerFrequency.Value.ToStr();
                    }
                    if (effect.SimpleInputEffect.AutoTriggerLimit is not null)
                    {
                        cbSimpleLimitAutoTriggers.Checked = true;
                        textSimpleAutoTriggerLimit.Text = effect.SimpleInputEffect.AutoTriggerLimit.Value.ToString();
                    }
                }
                AutoGeneratedName = GenerateName();

                Rebuild();
            }
        }

        private string AutoGeneratedName { get; set; } = "";
        private Keys SimpleKey { get; set; }

        public EventAction? Result { get; private set; }

        private void btnSimplePickKey_Click(object sender, EventArgs e)
        {

            using var form = new PickKeyForm();
            if (form.ShowDialog() == DialogResult.OK)
            {
                SimpleKey = form.Result;
                textSimpleKey.Text = PickKeyForm.KeysToString(form.Result);
                Rebuild();
            }

        }

        private void Rebuild()
        {
            btnOk.Enabled = false;



            var delay = textDelay.GetFloat(false);
            var triggerFrequency = textSimpleAutoTriggerFrequency.GetFloat(false);
            var autoTriggerLimit = textSimpleAutoTriggerLimit.GetInt();
            if (!cbSimpleAutoTriggerFrequency.Checked)
            {
                triggerFrequency = null;
            }
            else if (triggerFrequency is null || triggerFrequency.Value <= 0)
            {
                return;
            }
            if (SimpleKey == Keys.None)
            {
                return;
            }
            if (delay is null || delay.Value < 0)
            {
                return;
            }
            if (!cbSimpleLimitAutoTriggers.Checked || !cbSimpleLimitAutoTriggers.Checked)
                autoTriggerLimit = null;
            else if (autoTriggerLimit is null)
                return;

            if (textName.Text == AutoGeneratedName)
            {
                AutoGeneratedName = GenerateName();
                textName.Text = AutoGeneratedName;
            }
            if (string.IsNullOrWhiteSpace(textName.Text))
            {
                return;
            }

            btnOk.Enabled = true;
            Result = new EventAction(
                textName.Text.Trim(),
                delay.Value,
                SimpleInputEffect: new SimpleInputEffect
                (
                    Keys: SimpleKey,
                    AutoTriggerFrequency: triggerFrequency,
                    AutoTriggerLimit: autoTriggerLimit
                )
                );

        }

        private string GenerateName()
        {
            float? triggerFrequency;
            if (!cbSimpleAutoTriggerFrequency.Checked)
            {
                triggerFrequency = null;
            }
            else
                triggerFrequency = textSimpleAutoTriggerFrequency.GetFloat(false);
            return $"{textSimpleKey.Text}{(triggerFrequency is not null ? " (auto)" : "")}";
        }

        private void btnOk_Click(object sender, EventArgs e)
        {
        }

        private void AnyInputChanged(object sender, EventArgs e)
        {
            Rebuild();
        }

        private void textSimpleAutoTriggerFrequency_TextChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerFrequency.Checked = true;
            AnyInputChanged(sender, e);
        }

        private void textAutoTriggerLimit_TextChanged(object sender, EventArgs e)
        {
            cbSimpleLimitAutoTriggers.Checked = true;
            AnyInputChanged(sender, e);
        }

        private void cbSimpleAutoTriggerFrequency_CheckedChanged(object sender, EventArgs e)
        {
            cbSimpleLimitAutoTriggers.Enabled = cbSimpleAutoTriggerFrequency.Checked;
            textSimpleAutoTriggerLimit.Enabled = cbSimpleAutoTriggerFrequency.Checked && cbSimpleLimitAutoTriggers.Checked;
            AnyInputChanged(sender, e);
        }

        private void cbSimpleLimitAutoTriggers_CheckedChanged(object sender, EventArgs e)
        {
            textSimpleAutoTriggerLimit.Enabled = cbSimpleLimitAutoTriggers.Checked;
            AnyInputChanged(sender, e);
        }
    }
}
