using JoyMap.Extensions;
using JoyMap.Profile;
using JoyMap.Windows;

namespace JoyMap
{
    public partial class ActionForm : Form
    {
        public ActionForm(EventAction? effect = null)
        {
            InitializeComponent();
            comboSimpleKey.Configure(KeyOrButton.All);
            comboOnChangeRisingKey.Configure(KeyOrButton.All);
            comboOnChangeFallingKey.Configure([KeyOrButton.None, .. KeyOrButton.All]);




            if (effect is not null)
            {
                textName.Text = effect.Name;
                textDelay.Text = effect.DelayMs.ToStr();

                if (effect.SimpleInputEffect is not null)
                {
                    SimpleKey = effect.SimpleInputEffect.Keys;
                    comboSimpleKey.SelectedItem = SimpleKey;
                    if (effect.SimpleInputEffect.AutoTriggerFrequency is not null)
                    {
                        cbSimpleAutoTriggerFrequency.Checked = true;
                        textSimpleAutoTriggerFrequency.Text = effect.SimpleInputEffect.AutoTriggerFrequency.Value.ToStr();
                    }
                    if (effect.SimpleInputEffect.AutoTriggerTiming is not null)
                    {
                        cbSimpleAutoTriggerTiming.Checked = true;
                        textSimpleAutoTriggerHoldMs.Text = effect.SimpleInputEffect.AutoTriggerTiming.Value.HoldMs.ToStr();
                        textSimpleAutoTriggerReleaseMs.Text = effect.SimpleInputEffect.AutoTriggerTiming.Value.ReleaseMs.ToStr();
                    }
                    if (effect.SimpleInputEffect.AutoTriggerLimit is not null)
                    {
                        cbSimpleAutoTriggerLimit.Checked = true;
                        numericSimpleAutoTriggerLimit.Value = Math.Max(2, effect.SimpleInputEffect.AutoTriggerLimit.Value);
                    }
                    if (effect.SimpleInputEffect.AutoTriggerDelayMs is not null)
                    {
                        cbSimpleAutoTriggerDelayedStart.Checked = true;
                        textSimpleAutoTriggerDelayedStartMs.Text = effect.SimpleInputEffect.AutoTriggerDelayMs.Value.ToStr();
                    }
                    tabControl.SelectedTab = tpSimple;
                }
                else if (effect.ChangeTriggeredInputEffect is not null)
                {
                    RisingTriggerKey = effect.ChangeTriggeredInputEffect.Keys;
                    comboOnChangeRisingKey.SelectedItem = RisingTriggerKey;
                    textOnChangePressDurationMs.Text = effect.ChangeTriggeredInputEffect.PressDurationMs.ToStr();
                    if (effect.ChangeTriggeredInputEffect.FallingKeys is { } fallingKey)
                    {
                        cbOnChangeDifferentFallingKey.Checked = true;
                        FallingTriggerKey = fallingKey;
                        comboOnChangeFallingKey.SelectedItem = FallingTriggerKey;
                        UpdateFallingKeyEnabled();
                    }
                    tabControl.SelectedTab = tpTrigger;
                }
                AutoGeneratedName = GenerateName();

                Rebuild();
            }
        }

        private string AutoGeneratedName { get; set; } = "";
        private KeyOrButton SimpleKey { get; set; }
        private KeyOrButton RisingTriggerKey { get; set; }
        private KeyOrButton FallingTriggerKey { get; set; }

        public EventAction? Result { get; private set; }

        private void btnSimplePickKey_Click(object sender, EventArgs e)
        {

            using var form = new PickKeyForm();
            if (form.ShowDialog() == DialogResult.OK)
            {
                SimpleKey = KeyOrButton.From(form.Result);
                comboSimpleKey.SelectedItem = SimpleKey;
                Rebuild();
            }

        }

        private void Rebuild()
        {
            btnOk.Enabled = false;



            var delay = textDelay.GetFloat(false);
            if (delay is null || delay.Value < 0)
            {
                toolStripStatusLabel.Text = $"Unable to parse trigger delay";
                return;
            }

            if (textName.Text == AutoGeneratedName)
            {
                AutoGeneratedName = GenerateName();
                textName.Text = AutoGeneratedName;
            }
            if (string.IsNullOrWhiteSpace(textName.Text))
            {
                toolStripStatusLabel.Text = $"Trigger name is not set";
                return;
            }

            if (tabControl.SelectedTab == tpSimple)
            {


                var autoTriggerDelayedStartMs = textSimpleAutoTriggerDelayedStartMs.GetFloat(false);
                var triggerFrequency = textSimpleAutoTriggerFrequency.GetFloat(false);
                int? autoTriggerLimit = cbSimpleAutoTriggerLimit.Checked ? (int)numericSimpleAutoTriggerLimit.Value : null;
                var autoTriggerHoldMs = textSimpleAutoTriggerHoldMs.GetFloat(false);
                var autoTriggerReleaseMs = textSimpleAutoTriggerReleaseMs.GetFloat(false);
                AutoTriggerTiming? autoTriggerTiming = null;
                if (!cbSimpleAutoTriggerFrequency.Checked)
                {
                    triggerFrequency = null;
                }
                if (cbSimpleAutoTriggerTiming.Checked)
                {
                    if (autoTriggerHoldMs is null || autoTriggerHoldMs.Value <= 0)
                    {
                        toolStripStatusLabel.Text = $"Unable to parse auto-trigger hold time";
                        return;
                    }
                    else if (autoTriggerReleaseMs is null || autoTriggerReleaseMs.Value <= 0)
                    {
                        toolStripStatusLabel.Text = $"Unable to parse auto-trigger release time";
                        return;
                    }
                    autoTriggerTiming = new AutoTriggerTiming(autoTriggerHoldMs.Value, autoTriggerReleaseMs.Value);
                }
                if (!cbSimpleAutoTriggerDelayedStart.Checked)
                {
                    autoTriggerDelayedStartMs = null;
                }
                else if ((triggerFrequency is null || triggerFrequency.Value <= 0) && autoTriggerTiming is null)
                {
                    toolStripStatusLabel.Text = $"Unable to parse trigger frequency or timing";
                    return;
                }


                var key = comboSimpleKey.SelectedItem as KeyOrButton?;
                if (key is null)
                {
                    toolStripStatusLabel.Text = $"Simple trigger key/button is not set";
                    return;
                }

                Result = new EventAction(
                    textName.Text.Trim(),
                    delay.Value,
                    SimpleInputEffect: new SimpleInputEffect
                    (
                        Keys: key.Value,
                        AutoTriggerDelayMs: autoTriggerDelayedStartMs,
                        AutoTriggerFrequency: triggerFrequency,
                        AutoTriggerLimit: autoTriggerLimit,
                        AutoTriggerTiming: autoTriggerTiming
                    )
                    );
            }
            else if (tabControl.SelectedTab == tpTrigger)
            {
                var pressDurationMs = textOnChangePressDurationMs.GetFloat(false);
                if (pressDurationMs is null || pressDurationMs.Value <= 0)
                {
                    toolStripStatusLabel.Text = $"Unable to parse press duration";
                    return;
                }

                var key = comboOnChangeRisingKey.SelectedItem as KeyOrButton?;
                if (key is null)
                {
                    toolStripStatusLabel.Text = $"On-change rising key/button is not set";
                    return;
                }

                KeyOrButton? fallingKey = null;
                if (cbOnChangeDifferentFallingKey.Checked)
                {
                    fallingKey = comboOnChangeFallingKey.SelectedItem as KeyOrButton?;
                    if (fallingKey is null)
                    {
                        toolStripStatusLabel.Text = $"On-change falling key/button is not set";
                        return;
                    }
                }

                Result = new EventAction(
                    textName.Text.Trim(),
                    delay.Value,
                    ChangeTriggeredInputEffect: new ChangeTriggerInputEffect(
                        Keys: key.Value,
                        FallingKeys: fallingKey,
                        PressDurationMs: pressDurationMs.Value
                    ));
            }
            else
            {
                toolStripStatusLabel.Text = $"Bad effect selection";
                return;
            }
            toolStripStatusLabel.Text = $"Ok";
            btnOk.Enabled = true;

        }

        private string GenerateName()
        {
            if (tabControl.SelectedTab == tpSimple)
            {
                bool isAuto = cbSimpleAutoTriggerFrequency.Checked || cbSimpleAutoTriggerTiming.Checked;
                return $"{comboSimpleKey.Text}{(isAuto ? " (auto)" : "")}";
            }
            if (tabControl.SelectedTab == tpTrigger)
            {
                return comboOnChangeRisingKey.Text;
            }
            return "";
        }

        private void btnOk_Click(object sender, EventArgs e)
        {
        }

        private void AnyInputChanged(object sender, EventArgs e)
        {
            Rebuild();
        }

        private void textSimpleAutoTriggerFrequency_TextChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerFrequency.Checked = true;
            AnyInputChanged(sender, e);
        }

        private void numericSimpleAutoTriggerLimit_ValueChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerLimit.Checked = true;
            AnyInputChanged(sender, e);
        }

        private bool UpdatingAutoTriggerCheckboxes { get; set; }

        private void UpdateAutoTriggerDependents()
        {
            bool anyAutoMode = cbSimpleAutoTriggerFrequency.Checked || cbSimpleAutoTriggerTiming.Checked;
            cbSimpleAutoTriggerDelayedStart.Enabled =
                cbSimpleAutoTriggerLimit.Enabled =
                numericSimpleAutoTriggerLimit.Enabled =
                textSimpleAutoTriggerDelayedStartMs.Enabled = anyAutoMode;
            textSimpleAutoTriggerHoldMs.Enabled =
                textSimpleAutoTriggerReleaseMs.Enabled = cbSimpleAutoTriggerTiming.Checked;
        }

        private void cbSimpleAutoTriggerFrequency_CheckedChanged(object sender, EventArgs e)
        {
            if (UpdatingAutoTriggerCheckboxes) return;
            UpdatingAutoTriggerCheckboxes = true;
            try
            {
                if (cbSimpleAutoTriggerFrequency.Checked)
                    cbSimpleAutoTriggerTiming.Checked = false;
                UpdateAutoTriggerDependents();
            }
            finally
            {
                UpdatingAutoTriggerCheckboxes = false;
            }
            AnyInputChanged(sender, e);
        }

        private void cbSimpleAutoTriggerTiming_CheckedChanged(object sender, EventArgs e)
        {
            if (UpdatingAutoTriggerCheckboxes) return;
            UpdatingAutoTriggerCheckboxes = true;
            try
            {
                if (cbSimpleAutoTriggerTiming.Checked)
                    cbSimpleAutoTriggerFrequency.Checked = false;
                UpdateAutoTriggerDependents();
            }
            finally
            {
                UpdatingAutoTriggerCheckboxes = false;
            }
            AnyInputChanged(sender, e);
        }

        private void cbSimpleAutoTriggerLimit_CheckedChanged(object sender, EventArgs e)
        {
            AnyInputChanged(sender, e);
        }

        private void cbSimpleAutoTriggerDelayedStart_CheckedChanged(object sender, EventArgs e)
        {
            AnyInputChanged(sender, e);
        }

        private void textSimpleAutoTriggerDelayedStartMs_TextChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerDelayedStart.Checked = true;
            AnyInputChanged(sender, e);

        }

        private void textSimpleAutoTriggerHoldMs_TextChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerTiming.Checked = true;
            AnyInputChanged(sender, e);
        }

        private void textSimpleAutoTriggerReleaseMs_TextChanged(object sender, EventArgs e)
        {
            cbSimpleAutoTriggerTiming.Checked = true;
            AnyInputChanged(sender, e);
        }

        private void UpdateFallingKeyEnabled()
        {
            bool enabled = cbOnChangeDifferentFallingKey.Checked;
            labelOnChangeFallingKey.Enabled =
                comboOnChangeFallingKey.Enabled =
                btnOnChangeFallingKeyPick.Enabled = enabled;
        }

        private void cbOnChangeDifferentFallingKey_CheckedChanged(object sender, EventArgs e)
        {
            UpdateFallingKeyEnabled();
            AnyInputChanged(sender, e);
        }

        private void btnOnChangeRisingKeyPick_Click(object sender, EventArgs e)
        {
            using var form = new PickKeyForm();
            if (form.ShowDialog() == DialogResult.OK)
            {
                RisingTriggerKey = KeyOrButton.From(form.Result);
                comboOnChangeRisingKey.SelectedItem = RisingTriggerKey;
                Rebuild();
            }
        }

        private void btnOnChangeFallingKeyPick_Click(object sender, EventArgs e)
        {
            using var form = new PickKeyForm();
            if (form.ShowDialog() == DialogResult.OK)
            {
                FallingTriggerKey = KeyOrButton.From(form.Result);
                comboOnChangeFallingKey.SelectedItem = FallingTriggerKey;
                Rebuild();
            }
        }
    }
}
